feat: De-taggify
Change-Id: I97985c864e2f55b9408b3c409067540bead92efb

diff --git a/revancify b/revancify
--- a/revancify
+++ b/revancify
@@ -122,32 +122,26 @@ fetchSrc() {
 
     ping -c 1 google.com &> /dev/null || return
 
-    echo "Checking Latest Release..."
-
-    TAG=$(curl -s 'https://api.github.com/repos/someone5678/Revancify/releases/latest' 2> /dev/null | jq -r '.tag_name')
-
-    [ "$TAG" == "$VERSION" ] && return
-
-    echo "Revancify $TAG is available..."
-
-    echo "Installing..."
-
-    wget -qc "https://github.com/someone5678/Revancify/archive/refs/tags/$TAG.zip" -O "$TAG.zip"
-    if [ -e "$TAG.zip" ]; then
-        unzip -qo "$TAG.zip"
-        rm -rf "$TAG.zip"
-        for CONTENT in Revancify-*/* Revancify-*/.*; do
-            rm -rf "${SRC:?}/$(basename "$CONTENT")"
-            mv "$CONTENT" "$SRC/"
-        done
-        rm -rf Revancify-* &> /dev/null
-        cp -f "$SRC/revancify" "$PREFIX/bin/revancify"
-        chmod +x "$PREFIX/bin/revancify"
-        echo -e "Revancify $TAG is now installed.\nRun 'revancify -h' for help."
+    if [ ! -d Revancify ]; then
+        echo "Installing Revancify..."
+        if ! git clone https://github.com/someone5678/Revancify.git; then
+            echo -e "Unable to install Revancify !!\nPlease try again with proper Internet"
+            exit 1
+        fi
+        ln -sf "$SRC/revancify" "$PREFIX/bin/revancify"
+        echo -e "Revancify is now installed.\nRun 'revancify -h' for help."
         exit
     else
-        echo -e "Unable to install Revancify $TAG !!\nPlease try again with proper Internet"
-        exit 1
+        echo "Checking update..."
+        cd Revancify
+        if ! git fetch origin; then
+            echo -e "Unable to update Revancify !!\nPlease try again with proper Internet"
+            cd
+            exit 1
+        else
+            echo "Updating Revancify..."
+            git reset --hard origin/main
+        fi
     fi
 }
 
